[2023-08-18T01:32:43.380+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-08-18T01:32:42.279397+00:00 [queued]>
[2023-08-18T01:32:43.387+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-08-18T01:32:42.279397+00:00 [queued]>
[2023-08-18T01:32:43.387+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-18T01:32:43.395+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2023-08-18 01:32:42.279397+00:00
[2023-08-18T01:32:43.398+0000] {standard_task_runner.py:57} INFO - Started process 57 to run task
[2023-08-18T01:32:43.402+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_***_dag', 'spark_submit_task', 'manual__2023-08-18T01:32:42.279397+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/spark_jobs_dag.py', '--cfg-path', '/tmp/tmpdv75jy5h']
[2023-08-18T01:32:43.403+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask spark_submit_task
[2023-08-18T01:32:43.452+0000] {task_command.py:410} INFO - Running <TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-08-18T01:32:42.279397+00:00 [running]> on host 15ea5e9ca941
[2023-08-18T01:32:43.519+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_***_dag' AIRFLOW_CTX_TASK_ID='spark_submit_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-18T01:32:42.279397+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-18T01:32:42.279397+00:00'
[2023-08-18T01:32:43.529+0000] {spark_submit.py:218} INFO - Could not load connection string spark_local, defaulting to yarn
[2023-08-18T01:32:43.530+0000] {spark_submit.py:340} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark utils/spark_processing.py
[2023-08-18T01:32:43.622+0000] {spark_submit.py:491} INFO - /home/***/.local/lib/python3.10/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-08-18T01:32:44.653+0000] {spark_submit.py:491} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2023-08-18T01:32:44.655+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2023-08-18T01:32:44.656+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2023-08-18T01:32:44.657+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2023-08-18T01:32:44.657+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2023-08-18T01:32:44.658+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1094)
[2023-08-18T01:32:44.659+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1094)
[2023-08-18T01:32:44.659+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2023-08-18T01:32:44.660+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1111)
[2023-08-18T01:32:44.660+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1120)
[2023-08-18T01:32:44.661+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2023-08-18T01:32:44.690+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark utils/spark_processing.py. Error code is: 1.
[2023-08-18T01:32:44.694+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=spark_***_dag, task_id=spark_submit_task, execution_date=20230818T013242, start_date=20230818T013243, end_date=20230818T013244
[2023-08-18T01:32:44.703+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task spark_submit_task (Cannot execute: spark-submit --master yarn --name arrow-spark utils/spark_processing.py. Error code is: 1.; 57)
[2023-08-18T01:32:44.745+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-18T01:32:44.762+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
